---
- name: install nginx with basic html
  hosts: all

  vars:
    key_name: /home/ubuntu/dynokeys/key1
    ansible_user: ubuntu
    # ansible_ssh_private_key_file: ~/.ssh/von_upskilling_dev_86
    host_key_checking: False

  tasks:
    - name: update apt cache
      become: true
      apt:
        update_cache: yes

    - name: install ffmpeg
      become: true
      apt:
        name: ffmpeg
        state: latest
        update_cache: yes

    - name: install deps
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
        update_cache: yes
    - name: GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: repository docker
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: install docker
      become: true
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
    - name: adding users to group docker
      become: true
      user:
        name: '{{ item }}'
        groups: docker
        append: yes
      loop:
        - ubuntu

    - name: Install docker-compose
      become: true
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'
  
    - name: copy codefiles
      become: true
      copy:
        src: ./
        dest: /home/ubuntu/codefiles
        owner: ubuntu
        group: ubuntu
        mode: 0755
    - name: install golang
      become: true
      apt:
        name: golang
        state: latest
        update_cache: yes



    - name: download video
      get_url:
        url: 	https://d213lwr54yo0m8.cloudfront.net/0_232.mp4
        dest: /home/ubuntu/codefiles/video.mp4
    - name: download comment
      get_url:
        url: https://griffin-record-input.s3.amazonaws.com/335_comments_%40griffingaming.mp4
        dest: /home/ubuntu/codefiles/comment.mp4
        

  
  